CREATE OR REPLACE WAREHOUSE WH_LAB 
    WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE DB_LAB;

CREATE OR REPLACE SCHEMA DB_LAB.CHAT_APP;

CREATE TABLE IF NOT EXISTS DB_LAB.CHAT_APP.CONVERSATIONS (
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODEL STRING,
    ROLE STRING,
    CONTENT STRING
);

